"""Add ocr_text field to statements table

Revision ID: 07d3d067661f
Revises: 001_initial
Create Date: 2025-07-10 01:56:56.738249

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07d3d067661f'
down_revision = '001_initial'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('statements', sa.Column('ocr_text', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('statements', 'ocr_text')
    # ### end Alembic commands ### 